# Hand modified from generated model
# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-02-20T21:35:14+00:00
"""
Resources
https://www.faa.gov/documentLibrary/media/Order/7930.2T_Bsc_dtd_12_14_23_FINAL.pdf
https://www.faa.gov/air_traffic/flight_info/aeronav/notams/media/ICAO_NOTAM_Format_Example.pdf
https://www.faa.gov/air_traffic/flight_info/aeronav/notams/media/2021-09-07_ICAO_NOTAM_101_Presentation_for_Airport_Operators.pdf

https://aixm.aero/schema/5.1/event/Event_Features.xsd (Series Type,)
https://aixm.aero/schema/5.1/event/Event_DataTypes.xsd
https://aixm.aero/schema/5.1/AIXM_DataTypes.xsdhas 

"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Literal, NamedTuple, Optional, Set

from pydantic import BaseModel, ConfigDict, field_validator, alias_generators


class AdditionalGeometryData(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )
    pass
       


class HeightInformation(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )

    upperLevel: int
    uomUpperLevel: str
    lowerLevel: int
    uomLowerLevel: str


class NotamEvent(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )

    scenario: int


class Coordinate(NamedTuple):
    lat: float
    long: float




class Classification(Enum):
    FDC = 'FDC'
    INTL = 'INTL'
    DOM = 'DOM'
    LMIL = 'LMIL'
    MIL = 'MIL'



class Series(Enum):
    """
    The NOTAM series replaces the keywords previously used in the current domestic format
    
    B Aerodrome Maneuvering Areas RWY, TWY
    C Published Services COM, WX, ATC
    D Special Activity Airspace SAA
    E Airspace Events and Activities (PJE, Gliders etc.) PJE
    G Airways and Air Traffic Services Routes
    H Regulatory (TFR, Security) NOTAMs FDC, CARF
    I Apron/Ramp and Facilities APN
    J Obstructions (Crane, BLDG, Non-FCC Tower) OBST
    K FCC Obstructions (ASR assigned) OBST
    N Ground-Based Navigational Aids NAV
    R Field Condition (TALPA) NOTAM RWY
    V Published Instrument Procedures IFP
    Z Satellite Based Information GPS
    
    The FAA will utilize 13 different
    series for NOTAMs.
    The Department of Defense
    (DoD) uses F, L, M, V, W, and
    X Series for Military NOTAMs
    Source:
    https://www.faa.gov/air_traffic/flight_info/aeronav/notams/media/2021-09-07_ICAO_NOTAM_101_Presentation_for_Airport_Operators.pdf

    According to these documents Series can be any Character OR OTHER(:(\\w|_){1,58})?
    ie OTHER:a_b_c_d_12345
    https://aixm.aero/schema/5.1/event/Event_Features.xsd Has Series Type
    https://aixm.aero/schema/5.1/event/Event_DataTypes.xsd
    https://aixm.aero/schema/5.1/AIXM_DataTypes.xsdhas data type 
    """
    A = 'A' # Appears but undocumented
            # Appears in https://www.faa.gov/documentLibrary/media/Order/7930.2T_Bsc_dtd_12_14_23_FINAL.pdf
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F' # Department of Defense
    G = 'G'
    H = 'H'
    I = 'I'
    J = 'J'
    K = 'K'
    L = 'L' # Department of Defense
    M = 'M' # Department of Defense
    N = 'N'
    O = 'O' # Undocumented
    P = 'P' # Undocumented
    Q = 'Q' # Undocumented
    R = 'R'
    S = 'S' # Undocumented
    T = 'T' # Undocumented
    U = 'U' # Undocumented
    V = 'V' 
    W = 'W' # Department of Defense
    X = 'X' # Department of Defense
    Z = 'Z'


class NotamType(Enum):
    """
    The Action indicates the type of NOTAM. The example is a new NOTAM and is classified as a
    NOTAM

    Action Type of Notam
    N      Contains new information
    R      Replaces previous NOTAM
    C      Cancels previous non-auto cancel    
    """
    N = 'N'
    C = 'C'
    R = 'R'

class TrafficType(Enum):
    """
    This qualifier relates the NOTAM to a type of traffic and allows retrieval according to the user's needs.
    Depending on the NOTAM subject and content, the qualifier field TRAFFIC may contain the combined
    qualifiers. This example displays IV as the Traffic.

    Traffic Type of Traffic
    I Instrument Flight Rules (IFR)
    V Visual Flight Rules (VFR)
    K NOTAM is a Checklist
    """
    I = 'I'
    K = 'K'
    V = 'V'

class PurposeType(Enum):
    """
    Purpose
    The qualifier relates a NOTAM to certain purposes (intentions) and thus allows retrieval according to the
    user's requirements. Depending on the NOTAM subject and content, the qualifier field PURPOSE may
    contain combined qualifiers. This example displays NBO as the Purpose.
    
    Purpose Purpose description
    N       NOTAM selected for the immediate attention of aircraft operators
    B       NOTAM selected for pre-flight information briefing
    O       NOTAM concerning flight operations
    M       Miscellaneous NOTAM; not subject for briefing, but is available on request
    K       NOTAM is a Checklist
    """
    N = 'N'
    B = 'B'
    O = 'O'
    M = 'M'
    K = 'K'

class ScopeType(Enum):
    """
    The scope qualifiers are used to categorize NOTAMs. Depending on the NOTAM subject and content,
    the qualifier field SCOPE may contain combined qualifiers. This example uses A as the scope.
    Scope Scope Description
    A Aerodrome
    E Enroute
    W Navigation warning
    K Checklist
    """
    A = 'A'
    E = 'E'
    W = 'W'
    K = 'K'

class NotamTranslationType(Enum):
    LOCAL_FORMAT = 'LOCAL_FORMAT'
    ICAO = 'ICAO'


class ItemType(Enum):
    Feature = 'Feature'


class GeometryElement(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )

    type: Literal['Polygon'] | Literal['Point']
    subType: Optional[str] = None
    heightInformation: Optional[HeightInformation] = None
    coordinates: List[List[Coordinate]] |List[Coordinate] | Coordinate
    additionalGeometryData: Optional[AdditionalGeometryData] = None



class LocalTranslation(BaseModel):
    model_config = ConfigDict(
        alias_generator=alias_generators.to_camel,
        populate_by_name=True
    )
    type: Literal["LOCAL_FORMAT"]
    simple_text: str

class ICAOTranslation(BaseModel):
    model_config = ConfigDict(
        alias_generator=alias_generators.to_camel,
        populate_by_name=True
    )

    type: Literal["ICAO"]
    formatted_text: str



class ItemGeometry(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )
    type: Literal["GeometryCollection"]
    geometries: Optional[List[GeometryElement]] = None


class Notam(BaseModel):
    model_config = ConfigDict(
        extra = 'forbid',
        alias_generator=alias_generators.to_camel,
        populate_by_name=True,
    )
    
    @field_validator('traffic', 'purpose', 'scope', mode='before')
    @classmethod
    def set_from_str(cls, value: Any):
        """
        Converts str to to a set of characters.

        Ex: AWE => {'A', 'W', 'E'}

        Required because traffic, purpose, and scope fields are sets of characters represented as strings.
        Pydantic will never coerce str to Set so this function transforms the data to a set before Pydantic validates it.
        """
        if isinstance(value, str):
            return set(value)
        return value
    
    id: str
    number: str
    type: NotamType
    issued: datetime
    affectedFIR: Optional[str] = None 
    selection_code: Optional[str] = None
    traffic: Optional[Set[TrafficType]] = None
    purpose: Optional[Set[PurposeType]] = None
    scope: Optional[Set[ScopeType]] = None
    location: str
    effective_start: datetime
    effective_end: datetime | Literal["PERM"]
    text: str
    classification: Classification
    account_id: str
    last_updated: datetime
    icao_location: Optional[str] = None
    series: Optional[Series] = None
    minimumFL: Optional[str] = None
    maximumFL: Optional[str] = None
    schedule: Optional[str] = None
    coordinates: Optional[str] = None
    radius: Optional[str] = None
    lower_limit: Optional[str] = None
    upper_limit: Optional[str] = None


class CoreNOTAMData(BaseModel):
    model_config = ConfigDict(
        extra = 'forbid',
        alias_generator=alias_generators.to_camel,
        populate_by_name=True
    )

    notam_event: NotamEvent
    notam: Notam
    notam_translation: List[ICAOTranslation | LocalTranslation]


class Properties(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )

    coreNOTAMData: CoreNOTAMData


class APIItem(BaseModel):
    model_config = ConfigDict(
         extra = 'forbid'
    )

    type: ItemType
    properties: Properties
    geometry: Any


class APIResponseSuccess(BaseModel):
    model_config = ConfigDict(
        extra = 'ignore', # was forbid before
        alias_generator=alias_generators.to_camel,
        populate_by_name=True
    )

    page_size: int
    page_num: int
    total_count: int
    total_pages: int
    items: List[APIItem]


class APIResponseError(BaseModel):
    error: str

class APIResponseMessage(BaseModel):
    """
    API returns a message response provided invalid parameters
    """
    message: str
